<a href="https://colab.research.google.com/github/dhanyasharabha/Drowsiness-Detection/blob/main/DL_Lab_Exp_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
 a = [1,2,3,4,5]
a_numpy = np.array(a)
#Print an array
a_numpy


array([1, 2, 3, 4, 5])

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. It is an open source project and you can use it freely.

In [ ]:
#used to print shape of a list
a_numpy.shape

(5,)

In [ ]:
# Converting any data type to NumPy array
a = [(1,2), [3,4,(5)], (6,7,8)]
b = np.asarray(a)
b
b.shape

<ipython-input-4-36308d8795b0>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.asarray(a)


(3,)

In [ ]:
# Converting any data type to NumPy array
a = (1,2,3)
c=([1,2,3,4],4,5)
b = np.asarray(a)
d = np.asarray(c)
b
d

<ipython-input-5-27a07c5f5d49>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d = np.asarray(c)


array([list([1, 2, 3, 4]), 4, 5], dtype=object)

In [ ]:
#Get an n-dimensional array of zeros
a = np.zeros((3,4), dtype = np.float16)
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)

In [ ]:
#Get an n-dimensional array of ones
a = np.ones((3,4), dtype=np.int32)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [ ]:
a = np.full((3,3),2,dtype=np.int32)
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [ ]:
#Getting an array of evenly spaced values with np.arrange and np.linspace
np.linspace(1,5,num=5,endpoint=True,retstep=True)


(array([1., 2., 3., 4., 5.]), 1.0)

In [ ]:
np.arange(start=5,stop=10,step=2)

array([5, 7, 9])

A Tensor is a multi-dimensional array. Similar to NumPy ndarray objects, tf.Tensor objects have a data type and a shape. Additionally, tf.Tensors can reside in accelerator memory (like a GPU). TensorFlow offers a rich library of operations (for example, tf.math.add, tf.linalg.matmul, and tf.linalg.inv) that consume and produce tf.Tensors. These operations automatically convert built-in Python types. For example:

TensorFlow accepts data in the form of multi-dimensional arrays of higher dimensions called tensors. Multi-dimensional arrays are very handy in handling large amounts of data.

In [ ]:
#Tensorflow operations
import tensorflow as tf
print(tf.math.add(1., 2.))
print(tf.math.add([1, 2], [3, 4]))
print(tf.math.square(5))
print(tf.math.reduce_sum([1, 2, 3]))

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
print(tf.math.square(2) + tf.math.square(3))

tf.Tensor(13, shape=(), dtype=int32)


In [ ]:
x = tf.linalg.matmul([[2]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


Keras is the high-level API of TensorFlow 2: an approachable, highly-productive interface for solving machine learning problems, with a focus on modern deep learning. It provides essential abstractions and building blocks for developing and shipping machine learning solutions with high iteration velocity.

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [ ]:
#turning strings into sequences of integer word indices
from tensorflow.keras.layers import TextVectorization
training_data = np.array([["This is the vasavi"], ["the here's the 2nd sample."]])
training_data

array([['This is the vasavi'],
       ["the here's the 2nd sample."]], dtype='<U26')

In [ ]:
vectorizer = TextVectorization(output_mode="int")
vectorizer.adapt(training_data)
integer_data = vectorizer(training_data)
print(integer_data)

tf.Tensor(
[[4 6 2 3 0]
 [2 7 2 8 5]], shape=(2, 5), dtype=int64)


In [ ]:
from tensorflow.keras.layers import CenterCrop
from tensorflow.keras.layers import Rescaling

# Example image data, with values in the [0, 255] range
training_data = np.random.randint(0, 256, size=(64, 200, 200, 3)).astype("float32")

cropper = CenterCrop(height=100, width=100)
scaler = Rescaling(scale=1.0 / 255)

output_data = scaler(cropper(training_data))
print("shape:", output_data.shape)
print("min:", np.min(output_data))
print("max:", np.max(output_data))

shape: (64, 100, 100, 3)
min: 0.0
max: 1.0


pip3 install http://download.pytorch.org/whl/torch-0.3.0.post4-cp36-cp36m-macosx_10_7_x86_64.whl
pip3 install torchvision

In [ ]:
import torch
x = torch.Tensor(2, 3)  # An un-initialized Tensor object. x holds garbage data.
y = torch.rand(2, 3)    # Initialize with random values

# Operations

z1 = x + y
z2 = torch.add(x, y)             # Same as above

print(z2)


tensor([[0.7005, 0.8486, 0.6615],
        [0.0956,    nan, 0.4378]])


In [ ]:
import torch
x = torch.rand(2, 3)
y = torch.rand(2, 3)    # Initialize with random values

# Operations

z1 = x + y
z2 = torch.add(x, y)             # Same as above

print(z2)

tensor([[1.9192, 1.3635, 0.9819],
        [1.0526, 1.4693, 0.7160]])


In [ ]:
torch.is_tensor(z2)

True

In [ ]:
#Conversion between NumPy array to Tensor
a = np.array([1, 2, 3])
v = torch.from_numpy(a)
v

tensor([1, 2, 3])

In [ ]:
v = torch.randperm(4)
v

tensor([1, 3, 0, 2])

In [ ]:
v = torch.ones(10)
v

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
v = torch.ones(2, 1)
v

tensor([[1.],
        [1.]])

In [ ]:
v = torch.zeros(10)
v

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
eye = torch.eye(3)
v = torch.ones_like(eye)
v

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])